### ISSUE TITLE
YAML files miss imagePullSecrets

### ISSUE THREAD

**Issue by haraldmeyer** [SoftwareAG/terracotta-db-cloud#7]
In the documentation for running on Minikube a test-pull.yaml is created which includes the imagePullSecrets to fetch from Docker Store where the Terracotta DB images are located. In the actual yaml files in the repository though, this information is missing. Creating them thus fails.

**Comment by anthonydahanne** [comment]
hello,
yes, that's correct; it was "kind of" expected that the users would update their K8s manifests ; for example if users prefer storing the images on their own registry, they would not need to provide pull secrets - but sure, in the "normal" case, they would pull from Docker Store, and thus require secrets to be created and used.

I could simply fix this issue but that raises another question : should I rather maintain just 1 generic set of instructions for k8s deployment ? Best solution being a Helm chart that users would configure before installing.
